### ISSUE TITLE
Please add more colormaps

### ISSUE THREAD

**Issue by auxiliary** [seelabutk/pbnj#6]

**Comment by ahota** [comment]
Any color maps in particular?

So far I would like to add matplotlib's plasma and inferno to complete their "perceptually uniform" color maps.

**Comment by auxiliary** [comment]
Definitely yes to those two. But I wonder if we can get all Paraview colormaps in there.

**Comment by auxiliary** [comment]
or the Matplotlib ones actually. I feel like they're somewhat more standard.

**Comment by auxiliary** [comment]
@ahota With all colormaps we might want to put them in their own namespace or dictionary and check against their names instead of manually checking in `Configurations.cpp`. What do you think?
